version: '3.2'
services:
  main:
    image: property-helper:latest
    working_dir: '/app'
    command: ['node', 'src/index']
    depends_on:
      - redis
    ports:
      - 3000:3000
    networks:
      microservice-net:
  redis:
    image: redis:alpine
    networks:
      microservice-net:
networks:
  microservice-net:
